application: iohack2013
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /tasks/.*
  script: tasks.app
  login: admin
  auth_fail_action: redirect

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
